version: '3.8'
services:
  mongodb:
    image: mongo:latest #use the latest image.
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes: # optional to preserve database after container is deleted.
      - data:/data
  # Mongo Express Service
  mongo-express:
  image: mongo-express:latest #use the latest image. 
  container_name: mongo-express
  restart: unless-stopped
  # restart: always
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ME_CONFIG_MONGODB_SERVER: mongodb # use the name of Mongo Container above for server env var.
volumes:
data: {}

networks:
default:
name: mongodb_network